### ISSUE TITLE
Exception on Testnet.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [monaparty/counterparty-lib#1]
```
[2017-11-14 05:50:29][INFO] Block: 87947 (0.10s, hashes: L:45a40 / TX:92ce4 / M:42ae9)
[2017-11-14 05:52:47][WARNING] tx missing in rawtx cache: 'cb858fc0b804971cbe95e83325002eb8ae35e6d76efa163ec531935dfae977f7' -- txhash_list size: 4, hash: 90729db654a40556bd31e20709fea883 / raw_transactions_cache size: 15 / # rpc_batch calls: 4 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
[2017-11-14 05:52:47][WARNING] tx missing in rawtx cache: 'f6065aa06b3b84ac93dae1d6bed018fefca9c65d6d1ec90c15d3541d479d39f0' -- txhash_list size: 4, hash: 90729db654a40556bd31e20709fea883 / raw_transactions_cache size: 16 / # rpc_batch calls: 4 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
[2017-11-14 05:52:47][WARNING] tx missing in rawtx cache: '8b824a144ff04227fd7aa24dfda3fe63890e3f2c20989133d08b97e474460f7b' -- txhash_list size: 4, hash: 90729db654a40556bd31e20709fea883 / raw_transactions_cache size: 17 / # rpc_batch calls: 4 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
[2017-11-14 05:53:15][INFO] Block: 87948 (0.09s, hashes: L:2ab28 / TX:7ae97 / M:727c3)
[2017-11-14 05:54:05][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 157, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 412, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1299, in follow
    mempool_tx_index = list_tx(db, None, block_index, curr_time, tx_hash, tx_index=mempool_tx_index, tx_hex=tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 912, in list_tx
    source, destination, btc_amount, fee, data = get_tx_info(tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 450, in get_tx_info
    return _get_tx_info(tx_hex, block_parser, block_index)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 460, in _get_tx_info
    return  get_tx_info3(tx_hex, block_parser=block_parser)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 583, in get_tx_info3
    return get_tx_info2(tx_hex, block_parser=block_parser, p2sh_support=True)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 591, in get_tx_info2
    ctx = backend.deserialize(tx_hex)
  File "/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 83, in deserialize
    return bitcoinlib.core.CTransaction.deserialize(binascii.unhexlify(tx_hex))
TypeError: argument should be bytes, buffer or ASCII string, not 'NoneType'
```

**Comment by cryptcoin-junkey** [comment]
I close this issue because I couldn't reproduce it.
