### ISSUE TITLE
Testnet is down.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [monaparty/counterparty-lib#26]
Via https://twitter.com/fuyuton/status/1311688325393047552.

**Comment by cryptcoin-junkey** [comment]
The error log.

```
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 166, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 495, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1375, in follow
    tx_index = list_tx(db, block_hash, block_index, block_time, tx_hash, tx_index, tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1058, in list_tx
    source, destination, btc_amount, fee, data, decoded_tx = get_tx_info(tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 471, in get_tx_info
    return b'', None, None, None, None, _get_swap_tx(e.decodedTx, block_parser, block_index)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 532, in _get_swap_tx
    new_source, new_data = decode_p2w(asm)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 736, in decode_p2w
    return str(bech32), None
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/bech32.py", line 72, in __str__
    return encode(bitcoin.params.BECH32_HRP, self.witver, self)
AttributeError: 'MonaTestNetParams' object has no attribute 'BECH32_HRP'
```

 It looks caused by python-altpartylib. Lack of code around BECH32 support.

**Comment by cryptcoin-junkey** [comment]
This issue is resolved after applyiing https://github.com/monaparty/counterparty-lib/commit/ddbd18d0e07842eba089ccc64d4c5634b67eb262 .
